version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      STATIC_ROOT: /vol/static
      MEDIA_ROOT: /vol/media
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  caddy:
    image: caddy:2.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/vol/static:ro
      - media_data:/vol/media:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: unless-stopped

volumes:
  pg_data:
  static_data:
  media_data:
  caddy_data:
  caddy_config:
