# Generated by Django 5.2.7 on 2025-10-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "hero_title",
                    models.CharField(
                        default="Ingénierie • Industriel • TP", max_length=160
                    ),
                ),
                ("hero_subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "hero_cta_label",
                    models.CharField(
                        blank=True, default="Demander un devis", max_length=60
                    ),
                ),
                (
                    "hero_cta_url",
                    models.CharField(blank=True, default="#contact", max_length=200),
                ),
                (
                    "stat_1_label",
                    models.CharField(
                        blank=True, default="Années d'expérience", max_length=80
                    ),
                ),
                (
                    "stat_1_value",
                    models.CharField(blank=True, default="10+", max_length=40),
                ),
                (
                    "stat_2_label",
                    models.CharField(
                        blank=True, default="Projets livrés", max_length=80
                    ),
                ),
                (
                    "stat_2_value",
                    models.CharField(blank=True, default="50+", max_length=40),
                ),
                (
                    "stat_3_label",
                    models.CharField(blank=True, default="Partenaires", max_length=80),
                ),
                (
                    "stat_3_value",
                    models.CharField(blank=True, default="TCA…", max_length=40),
                ),
            ],
            options={
                "verbose_name": "Paramètres d'accueil",
                "verbose_name_plural": "Paramètres d'accueil",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="partners/")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("body", models.TextField()),
                ("published", models.BooleanField(default=True)),
                ("pub_date", models.DateField(auto_now_add=True)),
                ("cover", models.ImageField(blank=True, upload_to="blog/")),
            ],
            options={
                "ordering": ["-pub_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Nom d’icône (optionnel)", max_length=60
                    ),
                ),
                ("cover", models.ImageField(blank=True, upload_to="services/")),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("client", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("context", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("results", models.TextField(blank=True)),
                ("cover", models.ImageField(blank=True, upload_to="projects/")),
                (
                    "gallery",
                    models.ManyToManyField(blank=True, to="sitecontent.projectimage"),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
