# Generated by Django 5.2.7 on 2025-10-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homesettings",
            name="hero_bg",
            field=models.ImageField(blank=True, upload_to="home/"),
        ),
    ]
