# Generated by Django 5.2.7 on 2025-10-11 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0003_alter_projectimage_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="ANNOOR", max_length=160, verbose_name="Raison sociale"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="+227 …",
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+\\-\\s().]+$", "Format téléphone invalide."
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 22790000000 (chiffres uniquement si possible)",
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]+$", "Chiffres uniquement (indicatif compris)."
                            )
                        ],
                        verbose_name="WhatsApp (numéro)",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Adresse (ligne 1)"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="Niamey",
                        max_length=100,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="Niger", max_length=100, verbose_name="Pays"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                ("facebook", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("x_twitter", models.URLField(blank=True, verbose_name="X / Twitter")),
                (
                    "hours",
                    models.CharField(
                        blank=True,
                        default="Lun–Ven, 9h–18h (GMT+1)",
                        max_length=160,
                        verbose_name="Horaires",
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(blank=True, verbose_name="Google Maps Embed URL"),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Coordonnées du site",
                "verbose_name_plural": "Coordonnées du site",
            },
        ),
    ]
