# Generated by Django 5.2.7 on 2025-10-12 18:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sitecontent", "0004_sitecontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
